%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%                                                                    %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%    SNIPR:Single-NucleotIde-Specific Programmable Riboregulators    %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%    Fan Hong @ Green Lab                                            %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%    Biodesign Center for Molecular Design Biodesign and Biomimetics %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%    Arizona State University                                        %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%                                                                    %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

addpath('lib'); %add required helper functions to Matlab path
library_num = 3; % the number of the design libraries generated.
IS_PARALLEL = 1; % Set IS_PARALLEL = 1 if you want to run on your local computer using multiple cores; otherwise, set to 0
select_num = 5; % the number of top designs generated by the software from the libraries generated
SNP_TARGET = 1; % Set SNP_TARGET = 1 if you want to turn on the gene expression in the presense of mutant target; otherwise, set to 0

target_info = loadCSVabsFileRawtoStructure('input/target_input.csv','');
target_info(1,:) = [];

warning('off');

for c1 = 1:size(target_info,1)

    name = target_info{c1,1};
    WT_seq = target_info{c1,2}; % input the wild-type sequence
    SNP_seq = target_info{c1,3}; % input the mutant sequence
    protein_seq = target_info{c1,4}; % input the first 29 nucleotides of the downstream gene, for example lacZ
    
    %% STEP1. load sequence and generate design script
    Seq2Script(name,WT_seq,SNP_seq,protein_seq,SNP_TARGET)
    
    
    %% STEP2. Run design script to generate seq library
    DesignProcessing(name,library_num,IS_PARALLEL)
    
    %% STEP3. Extract the design library
    OutputProcessing(name)
    
    %% STEP4. Analysis and Screening for the best design
    
    EnergyAnalysis(name)
    DesignScreening(name,select_num)
    
end
